name: Python Test

on:
  push:
    branches:
      - main  # Adjust this based on your main branch name
  pull_request:
    branches:
      - main  # Adjust this based on your main branch name

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9  # Adjust the Python version as needed

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt 

    - name: Run Tests
      run: |
        python -m pytest 
        
